# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca0fc36bf21031e3ef9e4dcd01bb136579818bdc26332eb085127eec844cfab5f21e14f594ce6bcf789d8aa20921270366340d937db5a5a40a7f7dbbaf93077b

test:
  secret_key_base: 9ff83e00feb38c875557324ef92eed8189153d18089c33db3bfda4734185441649d0b3b84f816c5dddb4d1c3647b36bc7465011e905ffecb2417cccc5a91836e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
